version: '3.4'

x-astutodb-env: &astutodb-env
  environment:
    - POSTGRES_USER: yourpostgresusername
    - POSTGRES_PASSWORD: yourpostgrespassword

services:

  ghost_subdomain:
    image: ghost:5-alpine
    restart: always
    ports:
      - 8081:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: ghost_db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: https://sub.localhost
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    volumes:
      - ghost_subdomain:/var/lib/ghost/content

  ghost_path:
    image: ghost:5-alpine
    restart: always
    ports:
      - 8082:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: ghost_db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: https://subwithpath.localhost/blog
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    volumes:
      - ghost_path:/var/lib/ghost/content

  api1:
    ports:
      - 8083:8080
    environment:
      - INSTANCE_NAME=api1
    build:
      context: .
      dockerfile: ./Dockerfile-sampleapi

  api2:
    ports:
      - 8085:8080
    environment:
      - INSTANCE_NAME=api2
    build:
      context: .
      dockerfile: ./Dockerfile-sampleapi

  db:
    image: postgres:14.5
    environment: &db-env
      POSTGRES_USER: yourpostgresusername
      POSTGRES_PASSWORD: yourpostgrespassword
    volumes:
      - astuto_dbdata:/var/lib/postgresql/data
  astuto:
    image: riggraz/astuto:latest
    environment:
      <<: *db-env
      BASE_URL: https://astuto.localhost
      SECRET_KEY_BASE: yoursecretkeybase
    ports:
      - "8084:3000"
    depends_on:
      - db

  ghost_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ghost_db:/var/lib/mysql

  caddy:
    image: caddy:2.7.6
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019"
    volumes:
      - $PWD/testing/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/testing/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  ghost_subdomain:
  ghost_path:
  ghost_db:
  caddy_data:
  caddy_config:
  astuto_dbdata:

